added get_data function, fixed typos
david-klindt/NeuralLVM pull request #2
Opened 2022-03-09 13:49 UTC by MartinBjerke

2022-03-09 14:44 UTC, david-klindt commented on data_generation.py
> +    def generate_receptive_fields(self,z):
whitespace between ',' and 'z'

2022-03-09 14:46 UTC, david-klindt commented on data_generation.py
> +                rf_location = min_z + rf_location * (max_z - min_z)
above in line 73, can you split the expression over multiple lines to make it more readable? also whitespaces around '+' and after ','

2022-03-09 14:46 UTC, david-klindt commented on data_generation.py
> +    def generate_spikes(self,z,rf_location):
whitespaces after commas

2022-03-09 14:50 UTC, david-klindt requested changes
Please make test set noise free.
And some minor style fixes.

2022-03-09 14:50 UTC, david-klindt commented on data_generation.py
> +def get_data(num_neuron,
Please switch of the noise for the test set, so that might require separate calls to data_generation

2022-03-09 14:50 UTC, david-klindt commented on data_generation.py
> +             global_seed):
style for function arguments:

def fun(
   a,
   b,
   c
)

2022-03-09 14:50 UTC, david-klindt commented on data_generation.py
> +    data = data_generation(len_data=len_data_train+len_data_test,
whitespaces around +

2022-03-09 14:50 UTC, david-klindt commented on data_generation.py
> +    print("Generating latent\n")
latents plural?

2022-03-09 14:50 UTC, david-klindt commented on data_generation.py
> +    y_train = data.generate_spikes(z_train,rf)
whitespaces

2022-03-09 15:13 UTC, MartinBjerke commented on data_generation.py
> +def get_data(num_neuron,
Isn't the test set made noise free in line 141?

2022-03-11 12:39 UTC, david-klindt commented on data_generation.py
> +def get_data(num_neuron,
oops, yes you are right. My bad.

2022-03-11 12:40 UTC, david-klindt approved these changes
lgtm

2022-03-11 12:40 UTC, merged